/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author ricle
 */
@Component
@Scope("prototype")
public class CursoAdd extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoAdd.class.getName());

    private CursoIController controller;

    /**
     * Creates new form CursoAdd
     */
    @Autowired
    public CursoAdd(CursoIController controller) {
        super((java.awt.Frame) null, true);
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblCriarCurso = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCriarCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblCriarCurso.setText("Adicionando Curso");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Digite o nome do Curso");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigo.setText("Digite o Codigo do Curso");

        btnCriar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCriar.setText("Criar Curso");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigo)
                    .addComponent(txtNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNome)
                                .addComponent(tblCriarCurso))
                            .addComponent(lblCodigo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btnCriar)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tblCriarCurso)
                .addGap(41, 41, 41)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigo)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCriar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        Curso curso = new Curso();

        // Pega o texto que o usuário digitou no campo 'txtNome' 
        // e o armazena no objeto 'curso'.
        curso.setNome(txtNome.getText());

        // Pega o texto do 'txtCodigo' e armazena no objeto.
        curso.setCodigo(txtCodigo.getText());

        // Define um valor padrão (regra de negócio).
        // Como esta é uma tela de "Adicionar"
        curso.setAtivo(true);

        // --- ETAPA 2: TENTAR SALVAR NO BANCO DE DADOS ---
        // Usamos um bloco 'try...catch' porque operações de banco de dados
        // são "arriscadas" e podem falhar (ex: banco offline, código duplicado).
        try {
            
            controller.save(curso);

            // --- ETAPA 3: RESPOSTA DE SUCESSO ---
            // 5. Se a linha 'controller.salvar(curso)' NÃO deu erro (não lançou exceção),
            //    significa que o salvamento foi um sucesso.
            JOptionPane.showMessageDialog(this,
                    "Curso criado com sucesso",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            // 6. Linha CRUCIAL: Fecha esta janela (o JDialog).
            //    Isso "libera" a tela 'CursoListar' (que estava pausada)
            //    e permite que ela execute o "refresh" (o 'preencherTabela()').
            this.dispose();

        } catch (Exception e) {
            // --- ETAPA 4: RESPOSTA DE FALHA ---

            // 7. Se o 'controller.salvar()' lançou uma exceção ('throw e'),
            //    o código pula para este bloco 'catch'.
            JOptionPane.showMessageDialog(this,
                    "Falha ao salvar o curso: " + e.getMessage(), // Mostra a msg de erro
                    "Erro de Banco de Dados",
                    JOptionPane.ERROR_MESSAGE); // Mostra um ícone de erro.
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel tblCriarCurso;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
