/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author ricle
 */
@Component
@Scope("prototype")
public class CursoEdit extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoEdit.class.getName());

    private Curso cursoEditar;
    
    
    private CursoIController controller;
    /**
     * Creates new form CursoEdit
     */
    public CursoEdit(CursoIController controller) {
        super((java.awt.Frame) null, true); // JDialog modal sem parent
        this.controller = controller;
        initComponents();
        
    }
    
    public void setCurso(Curso curso) {
         this.cursoEditar = curso;
         preencherCampos();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblEditCurso = new javax.swing.JLabel();
        tblNomeEdit = new javax.swing.JLabel();
        txtNomeEdit = new javax.swing.JTextField();
        lblCodigoEdit = new javax.swing.JLabel();
        txtCodigoEdit = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblEditCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblEditCurso.setText("Editando Curso");

        tblNomeEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNomeEdit.setText("Insira o novo nome do curso");

        lblCodigoEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoEdit.setText("Insira o novo Codigo do Curso");

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setText("Editar Curso");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblEditCurso)
                            .addComponent(tblNomeEdit)
                            .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoEdit)
                            .addComponent(txtCodigoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnEdit)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tblEditCurso)
                .addGap(31, 31, 31)
                .addComponent(tblNomeEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigoEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //Pega o NOVO nome que o usuário digitou
        String novoNome = txtNomeEdit.getText();

        // 2. Validação simples (vê se o campo não está vazio)
        if (novoNome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "O nome do curso não pode ficar em branco.",
                    "Erro de Validação",
                    JOptionPane.WARNING_MESSAGE);
            return; // Para a execução
        }
        // 3. Atualiza o objeto 'cursoParaEditar' que está na memória
        this.cursoEditar.setNome(novoNome);
        // (Não precisamos mexer no código, pois ele não mudou)

        // 4. Tenta salvar a atualização no banco de dados
        try {
            
            controller.update(cursoEditar);

            //  Se deu certo, mostra mensagem de sucesso
            JOptionPane.showMessageDialog(this,
                    "Curso atualizado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            // FECHA esta tela (JDialog)
            //    Isso fará o código na 'CursoListar' (no btnEditar) continuar
            //    e atualizar a tabela.
            this.dispose();

        } catch (Exception e) {
            // Se o Controller deu erro (ex: nome duplicado, erro de banco)
            JOptionPane.showMessageDialog(this,
                    "Falha ao atualizar o curso: " + e.getMessage(),
                    "Erro de Banco de Dados",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    
             private void preencherCampos() {
        if (this.cursoEditar != null) {
            txtNomeEdit.setText(this.cursoEditar.getNome());
            txtCodigoEdit.setText(this.cursoEditar.getCodigo());
            txtCodigoEdit.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblCodigoEdit;
    private javax.swing.JLabel tblEditCurso;
    private javax.swing.JLabel tblNomeEdit;
    private javax.swing.JTextField txtCodigoEdit;
    private javax.swing.JTextField txtNomeEdit;
    // End of variables declaration//GEN-END:variables
}
