/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;

/**
 *
 * @author ricle
 */
public class CursoEdit extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoEdit.class.getName());

    private Curso cursoEditar;
    /**
     * Creates new form CursoEdit
     */
    public CursoEdit(java.awt.Frame parent, boolean modal, Curso curso) {
        super(parent, modal);
        initComponents();
        //this.cursoEditar = curso; // seta o curso que será editado
        //preencherCampos(); 
        this.cursoEditar = curso;

        // 2. Preenche os campos da tela
        preencherCampos();

        // 3. Centraliza a tela
        this.setLocationRelativeTo(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblEditCurso = new javax.swing.JLabel();
        tblNomeEdit = new javax.swing.JLabel();
        txtNomeEdit = new javax.swing.JTextField();
        lblCodigoEdit = new javax.swing.JLabel();
        txtCodigoEdit = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblEditCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblEditCurso.setText("Editando Curso");

        tblNomeEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNomeEdit.setText("Insira o novo nome do curso");

        lblCodigoEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoEdit.setText("Insira o novo Codigo do Curso");

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setText("Editar Curso");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblEditCurso)
                            .addComponent(tblNomeEdit)
                            .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoEdit)
                            .addComponent(txtCodigoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnEdit)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tblEditCurso)
                .addGap(31, 31, 31)
                .addComponent(tblNomeEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigoEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //Pega o NOVO nome que o usuário digitou
        String novoNome = txtNomeEdit.getText();

        // 2. Validação simples (vê se o campo não está vazio)
        if (novoNome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "O nome do curso não pode ficar em branco.",
                    "Erro de Validação",
                    JOptionPane.WARNING_MESSAGE);
            return; // Para a execução
        }
        // 3. Atualiza o objeto 'cursoParaEditar' que está na memória
        this.cursoEditar.setNome(novoNome);
        // (Não precisamos mexer no código, pois ele não mudou)

        // 4. Tenta salvar a atualização no banco de dados
        try {
            // 5. Cria o DAO
            CursoIDao cursoDAO = new CursoDao();

            // 6. Chama o novo método ATUALIZAR
            cursoDAO.update(this.cursoEditar);

            // 7. Se deu certo, mostra mensagem de sucesso
            JOptionPane.showMessageDialog(this,
                    "Curso atualizado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            // 8. FECHA esta tela (JDialog)
            //    Isso fará o código na 'CursoListar' (no btnEditar) continuar
            //    e atualizar a tabela.
            this.dispose();

        } catch (Exception e) {
            // 9. Se o DAO deu erro (ex: nome duplicado, erro de banco)
            JOptionPane.showMessageDialog(this,
                    "Falha ao atualizar o curso: " + e.getMessage(),
                    "Erro de Banco de Dados",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    
             private void preencherCampos() {
        if (this.cursoEditar != null) {
            txtNomeEdit.setText(this.cursoEditar.getNome());
            txtCodigoEdit.setText(this.cursoEditar.getCodigo());
            txtCodigoEdit.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Cria um "pai" e um "curso" falsos só para o 'main' funcionar
            Curso cursoFalso = new Curso();
            cursoFalso.setNome("Curso de Teste");
            cursoFalso.setCodigo("TST01");

            CursoEdit dialog = new CursoEdit(new javax.swing.JFrame(), true, cursoFalso);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblCodigoEdit;
    private javax.swing.JLabel tblEditCurso;
    private javax.swing.JLabel tblNomeEdit;
    private javax.swing.JTextField txtCodigoEdit;
    private javax.swing.JTextField txtNomeEdit;
    // End of variables declaration//GEN-END:variables
}
